# TensorFlow Fundamentals

In [46]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.0


#### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [9]:
vector = tf.constant([1,2,3])
print('Vector: ', end = "")
print(vector)

scalar = tf.constant(3)
print('Scalar: ', end = "")
print(scalar)

matrix = tf.constant([[1,2,3],[4,5,6]])
print('Matrix: ', end = "")
print(matrix)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Scalar: tf.Tensor(3, shape=(), dtype=int32)
Matrix: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


#### 2. Find the shape, rank and size of the tensors you created in 1.

In [14]:
print('Vector => Shape: {}; Rank: {}; Size: {}'.format(vector.shape, vector.ndim, tf.size(vector)))
print('Scalar => Shape: {}; Rank: {}; Size: {}'.format(scalar.shape, scalar.ndim, tf.size(scalar)))
print('Matrix => Shape: {}; Rank: {}; Size: {}'.format(matrix.shape, matrix.ndim, tf.size(matrix)))

Vector => Shape: (3,); Rank: 1; Size: 3
Scalar => Shape: (); Rank: 0; Size: 1
Matrix => Shape: (2, 3); Rank: 2; Size: 6


#### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [15]:
t1 = tf.random.uniform(shape = [5,300])
t2 = tf.random.uniform(shape = [5,300])

In [18]:
t1, t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.14536667, 0.9966215 , 0.59942234, ..., 0.08112013, 0.4435178 ,
         0.1150738 ],
        [0.76353574, 0.35006952, 0.9051237 , ..., 0.8912835 , 0.60403657,
         0.19606519],
        [0.46679473, 0.48350704, 0.24154925, ..., 0.863871  , 0.23964131,
         0.29052174],
        [0.06152213, 0.9110396 , 0.21887398, ..., 0.08912432, 0.51317954,
         0.3708626 ],
        [0.13824606, 0.5809865 , 0.55184746, ..., 0.8211254 , 0.0284127 ,
         0.5309553 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7006432 , 0.6101227 , 0.3691094 , ..., 0.25240707, 0.1267538 ,
         0.41963685],
        [0.4000703 , 0.81790304, 0.7141099 , ..., 0.42547143, 0.9388435 ,
         0.6888616 ],
        [0.9884585 , 0.5901401 , 0.6801081 , ..., 0.9355675 , 0.42212164,
         0.0743643 ],
        [0.6597357 , 0.8458383 , 0.65954745, ..., 0.57489896, 0.28047025,
         0.07709336],
        [0.84948

#### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [21]:
tf.matmul(t1, tf.transpose(t2)) # t2 must be transposed to match inner dimensions

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.93191 , 81.30072 , 78.46893 , 82.85084 , 77.08854 ],
       [75.692055, 77.72907 , 78.73748 , 82.781006, 79.853676],
       [74.57866 , 73.869415, 77.38354 , 76.44338 , 72.85747 ],
       [72.843285, 74.92688 , 75.300575, 77.33963 , 76.50084 ],
       [72.61388 , 73.775085, 74.475746, 78.17656 , 73.74274 ]],
      dtype=float32)>

In [22]:
# Alternative solution
tf.matmul(a=t1, b=t2, transpose_a=False, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.93191 , 81.30072 , 78.46893 , 82.85084 , 77.08854 ],
       [75.692055, 77.72907 , 78.73748 , 82.781006, 79.853676],
       [74.57866 , 73.869415, 77.38354 , 76.44338 , 72.85747 ],
       [72.843285, 74.92688 , 75.300575, 77.33963 , 76.50084 ],
       [72.61388 , 73.775085, 74.475746, 78.17656 , 73.74274 ]],
      dtype=float32)>

#### 5. Multiply the two tensors you created in 3 using dot product.

In [24]:
# Transpose and reshape give different values
tf.tensordot(t1, tf.transpose(t2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.93191 , 81.30072 , 78.46893 , 82.85084 , 77.08854 ],
       [75.692055, 77.72907 , 78.73748 , 82.781006, 79.853676],
       [74.57866 , 73.869415, 77.38354 , 76.44338 , 72.85747 ],
       [72.843285, 74.92688 , 75.300575, 77.33963 , 76.50084 ],
       [72.61388 , 73.775085, 74.475746, 78.17656 , 73.74274 ]],
      dtype=float32)>

In [27]:
tf.tensordot(t1, tf.reshape(t2, (300, 5)), axes = 1) # Equivalent to matrix multiplication with axes = 1

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.41582 , 83.41582 , 75.83809 , 78.868126, 80.554344],
       [77.131256, 84.00922 , 77.80853 , 76.60035 , 78.34891 ],
       [75.78443 , 78.92647 , 74.420685, 73.108986, 77.20211 ],
       [73.43348 , 80.24328 , 72.83789 , 73.63935 , 76.12943 ],
       [76.066124, 80.10658 , 72.61537 , 73.48934 , 77.09557 ]],
      dtype=float32)>

#### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [28]:
t3 = tf.random.uniform(shape = [224,224,3])
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.77368736, 0.05679345, 0.1551255 ],
        [0.24431407, 0.26763332, 0.87425125],
        [0.80820537, 0.12272811, 0.26018178],
        ...,
        [0.49735868, 0.70199573, 0.01618671],
        [0.597582  , 0.6264254 , 0.08093953],
        [0.97556424, 0.6489098 , 0.994004  ]],

       [[0.99722373, 0.74475586, 0.4281968 ],
        [0.46660256, 0.41416526, 0.3043779 ],
        [0.5266125 , 0.40625536, 0.2546097 ],
        ...,
        [0.14856946, 0.17556524, 0.15663123],
        [0.41591585, 0.48954403, 0.39670432],
        [0.7516278 , 0.36357784, 0.24577975]],

       [[0.4924556 , 0.7977481 , 0.3987521 ],
        [0.3259958 , 0.21984398, 0.13529742],
        [0.47242033, 0.11449802, 0.5223335 ],
        ...,
        [0.2789154 , 0.26294422, 0.8722068 ],
        [0.1292615 , 0.12695122, 0.48264337],
        [0.40513408, 0.15598667, 0.39451766]],

       ...,

       [[0.24456859, 0.20309865, 0.7976309 ],
        [0.81

#### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [33]:
print('Min => {}'.format(tf.reduce_min(t3[0, :, :])))
print('Max => {}'.format(tf.reduce_max(t3[0, :, :])))

Min => 0.0001481771469116211
Max => 0.99465012550354


#### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [55]:
t4 = tf.random.normal([1, 224, 224, 3], 5, 5)
squeezed_t4 = tf.squeeze(t4)
squeezed_t4.shape, squeezed_t4.ndim

(TensorShape([224, 224, 3]), 3)

#### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [65]:
t5 = tf.constant([1,2,3,4,534,6,7,8,9,10])
print(t5)
print('Index of maximum value: {}'.format(tf.argmax(t5)))

tf.Tensor([  1   2   3   4 534   6   7   8   9  10], shape=(10,), dtype=int32)
Index of maximum value: 4


#### 10. One-hot encode the tensor you created in 9.

In [66]:
tf.one_hot(t5, 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>